### ISSUE TITLE
Update plugin according to new changes

### ISSUE THREAD

**Issue by levice14** [CloudSlang/cs-intellij-plugin#14]
e.g. https://github.com/CloudSlang/cloud-slang/pull/974

the next release (~ `1.0.4`) will be a good candidate to use

**Comment by levice14** [comment]
release is out

**Comment by tethryus** [comment]
@Bonczidai At the moment, the new release does not bring new functionalities, that the plugin cannot handle, kind sir.

**Comment by chronical** [comment]
@tethryus @Bonczidai , do we need to update the support matrix inside the plugin?

**Comment by levice14** [comment]
which kind of support matix are we talking about?

**Comment by chronical** [comment]
AFAIK, for any new plugin we should mention its comaptibility matrix (eg: comaptible with cs language 1.0 0.9, 1.0.1 etc)

**Comment by tethryus** [comment]
@Bonczidai @chronical This is quite simple. Since we are using version 1.0,3 at the moment, the plugin will work with the same version that the builder and cli are working at the moment, when packaged with cloud-slang-content. As we release new versions of the dependencies needed to build the plugin, we should release another cs-intellij-plugin version, which will support the new cloud-slang-content, that will come packaged with let`s say 1.0.4 version of the CLI and builder.
